bot.name:
  Media_LoaderBot
bot.token:
  token
bot.admin:
  5540407547
bot.channel:
  -1001667984321

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1
    url: jdbc:postgresql://turntable.proxy.rlwy.net:21684/railway
    username: postgres
    password: DVCHSxceORgawMwmRvKnRpTmfuUQeDND
    #url: jdbc:postgresql://monorail.proxy.rlwy.net:39850/railway
    #username: postgres
    #password: kHHMEOcqeelVDLzGZGEYKaqnycgyBACa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8085}
